services:
  marble-api-mongo:
    volumes:
      - ${MARBLE_API_ENCRYPTION_KEY_FILE:?key file required}:/mongo-encrypt-key:ro
    command: ["mongod", "--enableEncryption", "--encryptionKeyFile", "/mongo-encrypt-key"]
